general:
  branches:
    ignore:
      - gh-pages

dependencies:
  pre:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
  override:
    - yarn

test:
  post:
    - yarn run test

deployment:
  staging:
    branch: master
    commands:
      - ./deploy.sh build