version: 2
jobs:
  build:
    docker:
      -image: circleci/node
    branches:
      ignore:
        - gh-pages
    steps:
      -checkout
      -run:
        name: install-yarn
        command: curl -o- -L https://yarnpkg.com/install.sh | bash
      -run:
        name: yarn
        command: yarn
      -run:
        name: tests
        command: yarn run test
      - deploy:
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ];
            then ./deploy.sh build;
          fi